### ISSUE TITLE
Sometimes failing to let a new post happen

### ISSUE THREAD

**Issue by andrewducker** [andrewducker/Postr#23]
com.postr.MessageLogger Severe: com.google.appengine.api.datastore.Entity cannot be cast to com.postr.DataTypes.User

E 2015-07-31 10:52:21.151

com.postr.LogHandler logException: Uncaught Exception : java.lang.ClassCastException: com.google.appengine.api.datastore.Entity cannot be cast to com.postr.DataTypes.User
    at com.postr.DataTypes.BaseSaveable.getParent(BaseSaveable.java:28)
    at com.postr.DataTypes.Outputs.BasePost.PostOrSave(BasePost.java:30)
    at com.postr.BaseOutputServlet.MakePost(BaseOutputServlet.java:46)
    at com.postr.BaseOutputServlet.ProcessRequest(BaseOutputServlet.java:24)
    at com.postr.BaseJSONServlet.handleRequest(BaseJSONServlet.java:85)
    at com.postr.BaseJSONServlet.doPost(BaseJSONServlet.java:51)

**Comment by andrewducker** [comment]
Looks like Objectify wasn't being registered every time.

Now should be!
